services:
  - type: web
    name: fresh
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium chromium-driver && \
      poetry install
    startCommand: poetry run start
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
